{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'petclinic'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['petclinic:9464']

      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel:8888']

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
---
{{- range .Values.monitoring.prometheus.persistence.claims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
    {{- include "petclinic.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.monitoring.prometheus.image.repository }}:{{ .Values.monitoring.prometheus.image.tag }}"
          ports:
            - containerPort: {{ .Values.monitoring.prometheus.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config
              subPath: prometheus.yaml
            - mountPath: /prometheus
              name: prometheus-data
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
{{- end }}