{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.monitoring.prometheus.service.port }}
  selector:
    app: prometheus
{{- end }}