apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
data:
  PORT: "8080"
  MYSQL_URL: "jdbc:mysql://mysql/petclinic"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel:4317"
  OTEL_SERVICE_NAME: "petclinic-service"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=petclinic-service"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_TRACES_SAMPLER: "parentbased_always_on"
  MANAGEMENT_SERVER_PORT: "9464"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "prometheus,health,info,metrics"
