{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlserver
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    app: mysqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlserver
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
        - name: mysqlserver
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            {{- toYaml .Values.mysql.env | nindent 12 }}
{{- end }}