{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysqlserver
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    app: mysqlserver
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306
  selector:
    app: mysqlserver
{{- end }}