apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 9411
              name: zipkin
            - containerPort: 16686
              name: ui
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
