apiVersion: v1
kind: Service
metadata:
  name: otel
  labels:
    app: otel
spec:
  type: ClusterIP
  selector:
    app: otel
  ports:
    - port: 13133
      targetPort: 13133
      name: health
    - port: 8888
      targetPort: 8888
      name: metrics
    - port: 8889
      targetPort: 8889
      name: exporter
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
