apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'petclinic'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['petclinic:9464']

      - job_name: 'mysql'
        static_configs:
          - targets: ['mysql:3306']

      - job_name: 'otel'
        static_configs:
          - targets: ['otel:8888']

      - job_name: 'jaeger'
        static_configs:
          - targets: ['jaeger:16686']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
data:
  rules.yml: |
    groups:
    - name: petclinic-alerts
      rules:
      - alert: HighErrorRate
        expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for more than 2 minutes"
