apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: ui
      port: 16686
      targetPort: 16686
  selector:
    app: jaeger
  type: ClusterIP
