services:

# Colector OpenTelemetry - Recopila métricas y trazas de los servicios

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./tools/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '13133:13133' # health_check extension
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
    networks:
      - monitor
    depends_on:
      - jaeger
      - prometheus


# Jaeger - Sistema de trazabilidad distribuida
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '4317:4317' # gRPC protocol
      - '9411:9411'
      - '16686:16686' # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitor

# Prometheus - Sistema de monitoreo y alertas
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./tools/prometheus/prometheus.yaml:/etc/prometheus.yaml
      - "./tools/prometheus/rules.yml:/etc/prometheus/rules.yml"
      - prometheus-data:/prometheus
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus.yaml
      - --enable-feature=otlp-write-receiver
    restart: always
    ports:
      - '9090:9090' # UI
    networks:
      - monitor


volumes:
  log-data:
    driver: local
  prometheus-data:


networks:
  monitor: