
services:
  petclinic:
    container_name: petclinic
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8080
      - 8000:8000
      - "9464:9464"  # Puerto para Prometheus metrics

    environment:
      - PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
      - OTEL_SERVICE_NAME=petclinic-service
      - OTEL_RESOURCE_ATTRIBUTES=service.name=petclinic-service
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_TRACES_SAMPLER=parentbased_always_on
      - MANAGEMENT_SERVER_PORT=9464
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=prometheus,health,info,metrics      

    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
    networks:
      - monitor   
  mysqlserver:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - monitor  
networks:
  monitor: