apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mysqlserver
  name: mysqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqlserver
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mysqlserver
    spec:
      containers:
        - env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_DATABASE
              value: petclinic
            - name: MYSQL_PASSWORD
              value: petclinic
            - name: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              value: petclinic
          image: mysql:8
          name: mysqlserver
          ports:
            - containerPort: 3306
              protocol: TCP
      restartPolicy: Always
