apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mysqlserver
  name: mysqlserver
spec:
  ports:
    - port: 3306
  selector:
    io.kompose.service: mysqlserver
