apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # o "1" si lo pones antes de petclinic
spec:
  project: default
  source:
    repoURL: https://github.com/yakindario/devops-petclinic.git
    targetRevision: main
    path: kubernetes/apps/monitoring/otel
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
