replicaCount: 1

image:
  repository: acrpetclinicdev.azurecr.io/petclinic
  tag: latest
  pullPolicy: IfNotPresent

service:
  httpPort: 80
  metricsPort: 9464

ingress:
  enabled: true
  hosts:
    app: petclinic.yakindario.me
    metrics: metrics.yakindario.me
    argocd: argocd.yakindario.me
  # puedes a침adir TLS si configuras cert-manager

metrics:
  path: /actuator/prometheus
  port: 9464

# Configuraci칩n de MySQL
mysql:
  enabled: true
  image:
    repository: mysql
    tag: "8"
  service:
    port: 3306
  env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "true"
    - name: MYSQL_DATABASE
      value: petclinic
    - name: MYSQL_PASSWORD
      value: petclinic
    - name: MYSQL_USER
      value: petclinic

# Configuraci칩n de monitoreo
monitoring:
  # OpenTelemetry Collector
  otel:
    enabled: true
    image:
      repository: otel/opentelemetry-collector-contrib
      tag: latest
    service:
      ports:
        - port: 13133
        - port: 8888
        - port: 8889
        - port: 4317
    persistence:
      enabled: true
      size: 100Mi

  # Jaeger
  jaeger:
    enabled: true
    image:
      repository: jaegertracing/all-in-one
      tag: latest
    service:
      ports:
        - port: 4317
        - port: 9411
        - port: 16686
    env:
      - name: COLLECTOR_OTLP_ENABLED
        value: "true"

  # Prometheus
  prometheus:
    enabled: true
    image:
      repository: prom/prometheus
      tag: latest
    service:
      port: 9090
    persistence:
      enabled: true
      claims:
        - name: prometheus-claim0
          size: 100Mi
        - name: prometheus-claim1
          size: 100Mi
        - name: prometheus-data
          size: 100Mi

# Variables de entorno para la aplicaci칩n principal
env:
  - name: PORT
    value: "8080"
  - name: MYSQL_URL
    value: jdbc:mysql://mysqlserver/petclinic
  - name: MANAGEMENT_SERVER_PORT
    value: "9464"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "prometheus,health,info,metrics"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel:4317"
  - name: OTEL_EXPORTER_OTLP_PROTOCOL
    value: "grpc"
  - name: OTEL_METRICS_EXPORTER
    value: "otlp"
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "service.name=petclinic-service"
  - name: OTEL_SERVICE_NAME
    value: "petclinic-service"
  - name: OTEL_TRACES_EXPORTER
    value: "otlp"
  - name: OTEL_TRACES_SAMPLER
    value: "parentbased_always_on"
