apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.fullname" . }}-service
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "petclinic.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 8080
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: 9464


