apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: acrpetclinicdev.azurecr.io/petclinic:latest
          ports:
            - containerPort: 8080
            - containerPort: 9464
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              value: petclinic
            - name: SPRING_DATASOURCE_PASSWORD
              value: petclinic
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-service:4317
            - name: OTEL_SERVICE_NAME
              value: petclinic-service
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=petclinic-service
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_TRACES_SAMPLER
              value: parentbased_always_on
            - name: MANAGEMENT_SERVER_PORT
              value: "9464"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: prometheus,health,info,metrics
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9464
            initialDelaySeconds: 60
            periodSeconds: 10
