apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: petclinic-project
  source:
    repoURL: 'https://github.com/your-repo/petclinic.git'
    targetRevision: HEAD
    path: kubernetes/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: petclinic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncWindow:
      schedule: "0 0 * * *"
      duration: 2h
  helm:
    parameters:
      - name: image.tag
        value: latest
      - name: mysql.password
        value: petclinic