apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: petclinic-project
  source:
    repoURL: "https://github.com/yakindario/devops-petclinic.git"
    targetRevision: HEAD
    path: kubernetes/base
    kustomize: {} # Cambiado de helm a kustomize
  destination:
    server: "https://kubernetes.default.svc"
    namespace: petclinic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
