apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - /etc/prometheus/rules.yml

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'petclinic'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['petclinic-service:9464']

      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-service:8888']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
data:
  rules.yml: |
    groups:
    - name: petclinic-rules
      rules:
      - alert: HighRequestLatency
        expr: http_server_requests_seconds_sum{uri!~"/actuator.*"} > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High request latency detected"
          description: "{{ $labels.instance }} has high HTTP latency ({{ $value }}s)"