apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--web.enable-lifecycle" # Corregido "lifestyle" a "lifecycle" si estaba mal
            - "--config.file=/etc/prometheus.yaml"
            # Quitar el flag problemático
            # - "--enable-feature=otlp-write-receiver"
            # Añadir path explícito para almacenamiento
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus.yaml
              subPath: prometheus.yaml
            - name: prometheus-rules
              mountPath: /etc/prometheus/rules.yml
              subPath: rules.yml
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-rules
          configMap:
            name: prometheus-rules
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-pvc
