apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: petclinic
  labels:
    app: prometheus-proxy
    azure.workload/name: "prometheus-proxy"
    azure.workload/type: "monitoring"
spec:
  type: ExternalName
  externalName: prometheus.monitoring.svc.cluster.local
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: web
