apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'petclinic'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['petclinic:9464']

      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel:8888']

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
