apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: <your-container-registry>/petclinic:latest
          ports:
            - containerPort: 8080
            - containerPort: 8000
            - containerPort: 9464
          env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysqlserver/petclinic
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel:4317
            - name: OTEL_SERVICE_NAME
              value: petclinic-service
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=petclinic-service
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_TRACES_SAMPLER
              value: parentbased_always_on
            - name: MANAGEMENT_SERVER_PORT
              value: "9464"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: prometheus,health,info,metrics
      imagePullSecrets:
        - name: <your-image-pull-secret>