apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: metrics
    - port: 9464
      targetPort: 9464
      protocol: TCP
      name: management
  selector:
    app: petclinic