resources:
  - ../../base
patches:
  - path: patch-deployment.yaml

namespace: petclinic

images:
  - name: your-docker-image-name
    newName: your-container-registry/your-docker-image-name
    newTag: latest
