apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: monitoring
  labels:
    azure.workload/name: "otel-collector-config"
    azure.workload/type: "monitoring"
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      # Añadir receptor para métricas de Kubernetes (mejora práctica para AKS)
      kubeletstats:
        collection_interval: 20s
        auth_type: "serviceAccount"
        endpoint: "${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 25
      
      # Añadir procesador de recursos para etiquetar con metadatos de Azure
      resource:
        attributes:
          - key: "cloud.provider"
            value: "azure"
            action: "upsert"
          - key: "k8s.cluster.name"
            value: "${env:CLUSTER_NAME}"
            action: "upsert"

    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: petclinic
        send_timestamps: true
        metric_expiration: 180m
        resource_to_telemetry_conversion:
          enabled: true

      logging:
        verbosity: detailed
        
      jaeger:
        endpoint: jaeger.default.svc.cluster.local:14250
        tls:
          insecure: true
        sending_queue:
          enabled: true
          num_consumers: 4
          queue_size: 100
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679
      # Añadir extensión para métricas de cluster de Kubernetes
      k8s_observer:
        auth_type: "serviceAccount"
        node: "${env:K8S_NODE_NAME}"

    service:
      telemetry:
        logs:
          level: info
        metrics:
          address: 0.0.0.0:8888
      extensions: [health_check, pprof, zpages, k8s_observer]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [jaeger, logging]
        metrics:
          receivers: [otlp, kubeletstats]
          processors: [memory_limiter, resource, batch]
          exporters: [prometheus, logging]
