apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: otel
  name: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otel
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: otel
    spec:
      containers:
        - args:
            - --config=/etc/otel-collector-config.yaml
          image: otel/opentelemetry-collector-contrib:latest
          name: otel
          ports:
            - containerPort: 13133
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
            - containerPort: 8889
              protocol: TCP
            - containerPort: 4317
              protocol: TCP  
          volumeMounts:
            - mountPath: /etc/otel-collector-config.yaml
              name: otel-claim0
      restartPolicy: Always
      volumes:
        - name: otel-claim0
          persistentVolumeClaim:
            claimName: otel-claim0
