apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel
  namespace: monitoring
  labels:
    app: otel
    azure.workload/name: "otel-collector"
    azure.workload/type: "monitoring"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
        azure.workload/name: "otel-collector"
        azure.workload/type: "monitoring"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8889"
    spec:
      containers:
        - name: otel
          image: otel/opentelemetry-collector-contrib:0.82.0
          args:
            - "--config=/conf/otel-collector-config.yaml"
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: prometheus
              containerPort: 8889
            - name: healthcheck
              containerPort: 13133
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: healthcheck
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: healthcheck
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config.yaml
                path: otel-collector-config.yaml
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
