apiVersion: v1
kind: Service
metadata:
  name: otel-service
spec:
  ports:
  - name: health-check
    port: 13133
    targetPort: 13133
  - name: metrics
    port: 8888
    targetPort: 8888
  - name: prometheus-export
    port: 8889
    targetPort: 8889
  - name: grpc
    port: 4317
    targetPort: 4317
  selector:
    app: otel-collector