{{- if .Values.monitoring.jaeger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.monitoring.jaeger.image.repository }}:{{ .Values.monitoring.jaeger.image.tag }}"
          env:
            {{- toYaml .Values.monitoring.jaeger.env | nindent 12 }}
          ports:
            {{- range .Values.monitoring.jaeger.service.ports }}
            - containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
{{- end }}