{{- if .Values.monitoring.otel.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    app: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: otel
    spec:
      containers:
        - name: otel
          image: "{{ .Values.monitoring.otel.image.repository }}:{{ .Values.monitoring.otel.image.tag }}"
          args:
            - --config=/etc/otel-collector-config.yaml
          ports:
            {{- range .Values.monitoring.otel.service.ports }}
            - containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - mountPath: /etc/otel-collector-config.yaml
              name: otel-config
              subPath: otel-collector-config.yaml
      volumes:
        - name: otel-config
          configMap:
            name: otel-config
{{- end }}