apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitor
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'petclinic'
        static_configs:
          - targets: ['petclinic:8080']

      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel:8888']

      - job_name: 'jaeger'
        static_configs:
          - targets: ['jaeger:16686']

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    rule_files:
      - "/etc/prometheus/rules.yml"